#!/usr/bin/env python
#-*- coding: utf-8 -*-
"""Easy Dojo

Simple tool to help in Coding Dojo sessions

Usage:
  easy_dojo init <name>
  easy_dojo watch [--handlers=<handlers>] [<args>...]
  easy_dojo panel [<port>]
  easy_dojo list
  easy_dojo (-h | --help)
  easy_dojo --version

Options:
  --handlers=<handlers>     Handlers used on watch command(separated by commas)
  port    Port used on tornado server of EasyDojo Panel(default=2020)
  -h --help     Show this screen.
  --version     Show version.

"""
from docopt import docopt

from easydojo import __title__, __version__
from easydojo.commands import DojoCommand


if __name__ == '__main__':
    arguments = docopt(__doc__, version='{0} {1}'.format(__title__, __version__))
    command = DojoCommand.make(arguments)
    command.run()
